package ex.try_catch_finally.atomic_tx;

public class TryAgainException extends Exception {}
